HACKEREARTH_SKILL_TAXONOMY = {
    "Programming Languages": [
        ".NET",
        ".NET 8.0",
        ".NET Azure",
        ".Net Framework",
        ".Net Microservices",
        ".NET Standard",
        "Advanced Java",
        "ASP.NET",
        "ASP.NET Core 6.0",
        "ASP.NET MVC",
        "Assembly Language",
        "Basic Programming",
        "C",
        "C#",
        "C# Advanced",
        "C++",
        "Clojure",
        "COBOL",
        "Core Java",
        "Dart",
        "Delphi",
        "Elixir",
        "Embedded C",
        "F#",
        "Go",
        "Java",
        "Java Concurrency",
        "Java Enterprise Edition",
        "Java Microservices",
        "Java Multithreading",
        "Java Scalability",
        "Java Struts",
        "JavaScript",
        "Julia",
        "Kotlin",
        "MATLAB",
        "Objective-C",
        "Perl",
        "PHP",
        "PL/SQL",
        "PowerShell Scripting",
        "Python",
        "Python 3",
        "Python only",
        "Python Scripting",
        "R",
        "Regexp",
        "Ruby",
        "SAP ABAP",
        "Scala",
        "Scripting",
        "Specific Java Questions",
        "Swift",
        "Swift 5",
        "T-SQL",
        "TypeScript",
        "VB.NET",
        "VC++",
        "Verilog",
        "VHDL",
    ],
    "Web Frontend": [
        "AlpineJS",
        "Angular",
        "AngularJS",
        "AngularJS 2",
        "Ant Design",
        "Babel",
        "Blazor",
        "BlueprintJS",
        "Cascading Style Sheets",
        "Chakra UI",
        "CSS",
        "EmberJS",
        "ESLint",
        "ExtJS",
        "HTML",
        "HTML CSS only",
        "Jest",
        "Jinja",
        "JQuery",
        "Kendo UI using Jquery",
        "LEMP",
        "Less",
        "Mean",
        "MERN",
        "MEVN",
        "NextJS",
        "NgRx",
        "NuxtJS",
        "Progressive Web Apps",
        "React Native",
        "ReactJS",
        "Sass",
        "Tachyons",
        "Tailwind CSS",
        "ThreeJS",
        "UnoCSS",
        "Vanilla.js",
        "Vite",
        "VueJS",
        "Web components",
        "Web Development",
        "Web technologies",
        "Webpack",
        "Windi CSS",
        "Windows Presentation Foundation",
        "WPF",
    ],
    "Backend Frameworks & APIs": [
        "API Design",
        "API Services",
        "API Testing",
        "CodeIgniter",
        "Django",
        "EF Core",
        "ExpressJS",
        "Flask",
        "Grails",
        "Hibernate",
        "HTTP Interceptors",
        "JSP",
        "Laravel",
        "LINQ",
        "Micro Frontend Architecture",
        "MicroServices",
        "NestJS RESTful APIs",
        "NodeJS",
        "Openapi",
        "REST API",
        "Ruby on Rails",
        "SOAP",
        "SOAP APIs",
        "Spring",
        "Spring Boot",
        "Spring Ecosystem",
        "Struts",
        "Swagger",
        "Symfony",
        "WCF",
        "Web services",
    ],
    "Mobile Development": [
        "Android",
        "App Store Optimization",
        "Cross-platform Development",
        "Flutter",
        "Ionic",
        "Mobile development",
        "Mobile Security",
        "Mobile testing",
        "Mobile UI/UX Design",
        "SwiftUI",
        "Xamarin",
    ],
    "Cloud Platforms": [
        "Advanced Cloud Infrastructure",
        "Alibaba",
        "Amazon Web Services",
        "AWS",
        "AWS CLI",
        "AWS Glue",
        "Azure",
        "Azure Bicep",
        "Azure Devops",
        "Cloud composer",
        "Cloud Computing",
        "Cloud fundamentals",
        "Cloud Infrastructure",
        "Cloud Migration",
        "Cloud Native ETL",
        "Digital ocean",
        "FinOps",
        "Google Cloud",
        "Google Cloud Platform",
        "Microsoft Azure",
        "Multi Cloud Strategy",
        "Serverless Architecture",
    ],
    "DevOps, Infra & CI/CD": [
        "AIX",
        "Ansible",
        "Apache Maven",
        "ARM Templates",
        "Backup and Recovery",
        "Confluence",
        "ControlM",
        "Crontab",
        "Datadog",
        "Desktop Support",
        "DevOps",
        "DevSecOps",
        "Disaster Recovery Planning",
        "Docker",
        "Dynatrace",
        "ELK Stack",
        "Envoy Proxy",
        "Git",
        "GitHub",
        "Gitops",
        "Gradle",
        "Grafana",
        "Hyper V",
        "Istio",
        "IT / System Administration",
        "IT Support and Operations",
        "Jenkins",
        "JIRA",
        "JumpCloud",
        "Kibana",
        "Kubernetes",
        "Linux",
        "Linux Administration",
        "Linux Server Configuration",
        "macOS Administration",
        "Monitoring-tool",
        "New Relic",
        "Prometheus",
        "Service Mesh",
        "Splunk",
        "Storage",
        "System Administration",
        "System Monitoring",
        "System Troubleshooting",
        "Technical Issue Troubleshooting",
        "Terraform",
        "TFS",
        "Ubuntu",
        "Unix",
        "Veeam",
        "Visual Studio",
        "VMware",
        "VMware vSphere",
        "Windows Server Administration",
    ],
    "Databases & Data Storage": [
        "Cassandra",
        "CouchDB",
        "Cypher",
        "Database",
        "Database Administration",
        "Database Management System",
        "DBMS",
        "Dbt",
        "dbt Python",
        "Greenplum",
        "Indexing",
        "LIMS",
        "MongoDB",
        "MySQL",
        "Neo4j",
        "NoSQL",
        "Oracle",
        "Oracle Business Intelligence",
        "PostgreSQL",
        "Prepared Statements",
        "Redis",
        "Snowflake",
        "Spatial Databases",
        "SQL",
        "SQL Server",
        "SQL Server Analysis Services",
        "SQL Server Integration Services",
        "SQL Server Reporting Services",
        "Teradata",
    ],
    "Data Engineering & Big Data": [
        "ActiveMQ",
        "Apache Beam",
        "Apache Camel",
        "Apache Griffin",
        "Apache Hive",
        "Apache Superset",
        "Apache Zeppelin",
        "Big Data",
        "Big Query",
        "Data Engineering",
        "Data Engineering & Analytics",
        "Data Lakehouse",
        "Data Literacy",
        "Data Mesh",
        "Data Migration",
        "Data Modeling",
        "Data Proc",
        "Data Processing",
        "Data Solutions",
        "Data Warehousing",
        "Databricks",
        "EMR",
        "ETL",
        "Google BigQuery",
        "Hadoop",
        "HDFS",
        "Informatica",
        "Informatica PowerCenter",
        "Kafka",
        "Master Data Management",
        "Message queues",
        "Mulesoft",
        "Pipeline",
        "Pipeline Configuration",
        "RabbitMQ",
        "Realtime Processing",
        "Reverse ETL",
        "Snowpipe",
        "Spark",
        "Spark Code",
        "Spark Dataframes",
        "Spark SQL",
        "Talend",
    ],
    "Data Science, Analytics & ML": [
        "A/B Testing",
        "A/B Testing for ML",
        "Anomaly Detection",
        "Bayesian Statistics",
        "Business Intelligence",
        "Business Intelligence & Reporting",
        "Business Intelligence Tools",
        "CatBoost",
        "Cognos Analytics",
        "Crystal Reports",
        "Data Analysis and Manipulation",
        "Data analytics",
        "Data Analytics & Visualization",
        "Data Analytics Tools",
        "Data frames",
        "Data Science",
        "Exploratory Data Analysis",
        "Gradient Boosting",
        "IBM Cognos Business Intelligence",
        "Jupyter Notebooks",
        "LightGBM",
        "LookML",
        "Machine Learning",
        "Machine Learning Operations",
        "MicroStrategy",
        "Power BI",
        "PySpark",
        "Qlik Sense",
        "QlikView",
        "QlikView Set Analysis",
        "Quantitative Analysis",
        "Quantum Machine Learning",
        "Reinforcement learning",
        "SAS",
        "SciPy",
        "Semantic Search",
        "SSAS",
        "SSRS",
        "Statistical Inference",
        "Tableau",
        "Time Series Forecasting",
    ],
    "Generative AI, LLM & Agentic AI": [
        "Advanced AI",
        "Advanced RAG Patterns",
        "Agentic AI",
        "Agentic Systems",
        "AI",
        "AI Act Compliance",
        "AI Auditing",
        "AI Ethics",
        "AI Ethics and Evaluation",
        "AI Research Modelling and Data Readiness",
        "amelia",
        "Artificial Intelligence",
        "AutoML",
        "Chatbot",
        "Chatbot Development",
        "Conversational AI",
        "Embeddings",
        "Explainable AI",
        "Federated Learning",
        "Function Calling in LLMs",
        "Generative AI",
        "GraphAI",
        "Langchain",
        "LangGraph",
        "Large Context Model",
        "Large Language Model",
        "Llama 2",
        "Llama 3",
        "LlamaIndex",
        "LlamaIndex.TS",
        "LLM",
        "Memory Architectures for AI Agents",
        "MLflow",
        "Model Context Protocol",
        "Model Governance",
        "Model Lifecycle Management",
        "Multi-Agent Coordination",
        "One Reach AI",
        "Open Source LLMs",
        "Prompt Engineering",
        "Retrieval-Augmented Generation",
        "Speech Synthesis",
        "Stable Diffusion",
        "Text-to-Image Generation",
        "Tool Use in LLMs",
        "Transfer learning",
        "Voice Experience",
        "Voice Recognition",
    ],
    "Testing & QA": [
        "Automation Testing",
        "Automations",
        "CodeceptJS",
        "Cucumber",
        "Cucumber only",
        "Cypress",
        "Database testing",
        "ETL Testing",
        "Gatling",
        "JMeter",
        "JUnit",
        "JUnit5",
        "Karate API",
        "Load balancer/testing",
        "Manual Testing",
        "Playwright",
        "QA",
        "Quality Assurance",
        "Quality control",
        "Rest Assured",
        "Robot Framework",
        "Security testing",
        "Selenium",
        "Selenium WebDriver",
        "Software Testing",
        "TDD",
        "Test Automation",
        "Test Driven Development",
        "Testing",
        "Testing & Quality Assurance",
        "TestNG",
        "Validation and Verification",
        "Xray",
        "Xray for Jira",
        "Xray Test Management for Jira",
    ],
    "Security & Cybersecurity": [
        "Cyber Security",
        "CyberOps",
        "Cybersecurity Fundamentals",
        "Data Privacy and Protection",
        "GDPR Compliance",
        "ifconfig",
        "IoT Security",
        "JWT",
        "net-tools",
        "netstat",
        "nikto",
        "nmap",
        "Phishing Investigations",
        "Red Teaming",
        "Reverse DNS",
        "Security",
        "Security Settings Management",
        "SecurityOps",
        "SSL",
        "VPN Configuration",
    ],
    "Networking & Systems": [
        "5G Technology",
        "Active Directory",
        "ARP",
        "Asterisk",
        "Bandwidth Management",
        "CCNA",
        "CCNP",
        "Cisco Meraki",
        "Citrix",
        "DHCP",
        "DNS Management",
        "LDAP",
        "Load balancing",
        "Network",
        "Network Automation",
        "Network Monitoring",
        "Network Troubleshooting Techniques",
        "Networking",
        "Networking Principles",
        "Protocols",
        "SD WAN",
        "Sensor Networks",
        "User Account Management",
        "User and Group Management",
    ],
    "Blockchain & Web3": [
        "General Binance Smart Chain",
        "Bitcoin",
        "Blockchain",
        "Blockchain & Web3",
        "Blockchain Technology",
        "Crypto Assets",
        "Cryptocurrency",
        "Cryptocurrency Trading",
        "Decentralised Finance",
        "Digital Assets",
        "Hyperledger",
        "Nft",
        "Polygon",
        "Quantum Cryptography",
        "Smart Contracts",
        "Token",
        "Web3",
        "Decentralized Applications (DApps)",
        "Decentralized Finance (DeFi)",
        "NFTs & Token Standards",
        "Blockchain Scalability & Interoperability",
        "Backend Integration",
        "DApp Deployment",
        "Event Handling",
        "Frontend Integration",
        "IPFS & Decentralized Storage",
        "Wallet Integration (MetaMask, WalletConnect)",
        "Web3.js & Ethers.js",
        "Automated Market Makers (AMMs)",
        "Flash Loans",
        "Lending & Borrowing Protocols",
        "Liquidity Pools",
        "Stablecoins",
        "Staking",
        "Yield Farming",
        "ERC-1155 Multi-Token Standard",
        "ERC-20 Tokens",
        "ERC-721 NFTs",
        "Governance Tokens",
        "NFT Marketplaces",
        "NFT Minting",
        "Tokenomics",
        "Contract Deployment",
        "Gas Optimization",
        "Smart Contract Development",
        "Smart Contract Security",
        "Smart Contract Testing",
        "Solidity Programming",
        "Upgradeable Contracts",
        "Blockchain Interoperability Protocols",
        "Cross-Chain Bridges",
        "Cross-Chain Messaging",
        "Layer 2 Solutions",
        "Optimistic Rollups",
        "Sidechains",
        "ZK Rollups",
    ],
    "IoT, Embedded & Robotics": [
        "Ardiono Uno",
        "Arduino",
        "Autocad",
        "AUTOSAR",
        "Boolean Algebra",
        "Digital electronics",
        "Edge Computing",
        "Embedded system",
        "Flip flops",
        "GPS Development",
        "HMI",
        "Industrial Internet of Things",
        "Internet of Things",
        "IoT & Edge Computing",
        "LabView",
        "Location-Based Services",
        "LoRaWAN",
        "MCITP",
        "Microprocessor",
        "Module Compilation and Loading",
        "Mqtt",
        "RaspBerry Pi",
        "Robot Kinematics",
        "Robot Sensor Integration",
        "Robotics Programming Actuator Control",
        "ROS Framework",
        "SCADA",
        "Simulink",
        "SolidWorks",
        "Transducers",
        "VLSI Design",
        "Zigbee",
    ],
    "AR/VR & Game Development": [
        "3D Modeling",
        "3DEXPERIENCE",
        "AR/VR & Gaming",
        "ARcore",
        "ARKit",
        "Augmented Reality",
        "Augmented Reality and Virtual Reality",
        "Extended Reality",
        "Game Development",
        "HoloLens Development",
        "Mixed Reality",
        "Oculus SDK",
        "Unity",
        "Unity 3D",
        "Virtual Reality",
        "Webxr",
    ],
    "Enterprise Platforms (ERP/CRM/Low-code)": [
        "Adobe",
        "Apache",
        "Appian",
        "Avaya Contact Center",
        "BigCommerce",
        "BizTalk Server",
        "Boomi",
        "Bubble",
        "Contentful",
        "Drupal",
        "Drush",
        "E-commerce Platforms",
        "Enterprise Integration",
        "Enterprise Service Bus",
        "IBM WebSphere",
        "Integration Cloud",
        "Jahia",
        "JBoss",
        "JDA WMS",
        "Kofax",
        "Liferay Portal",
        "Low Code No Code Platforms",
        "MadCap Flare",
        "Magento",
        "Mendix",
        "Microsoft Dynamics 365",
        "Microsoft Power Automate",
        "Microsoft Power Automate Advanced",
        "Microsoft Power Platform",
        "MS Dynamics",
        "MS SSIS",
        "OpenCart",
        "Oracle Commerce",
        "Oracle ERP",
        "Oracle SOA Suite",
        "Outsystems",
        "Payment Gateways",
        "Pega",
        "Power Apps",
        "Power Automate",
        "PrestaShop",
        "Process Cloud Service",
        "Reltio",
        "SailPoint",
        "SalesForce",
        "Salesforce Commerce Cloud",
        "Salesforce lightning",
        "Salesforce Marketing Cloud",
        "SAP",
        "SAP BASIS",
        "SAP FICO",
        "SAP HANA",
        "SAP Hybris",
        "ServiceNow",
        "SFMC",
        "Shopify",
        "Strapi",
        "TIBCO",
        "Twilio",
        "Windchill",
        "WooCommerce",
        "WordPress",
        "Workday",
        "Zapier",
        "Zend",
    ],
    "RPA & Automation Tools": [
        "ActiveVOS",
        "Automated Systems",
        "Automation Anywhere",
        "Blue Prism",
        "RPA",
        "UIPATH",
        "Workfusion",
    ],
    "CS Fundamentals & Theory": [
        "Algorithms",
        "Architectural Design Patters",
        "Behavioral Design Patterns",
        "CAP Theorem",
        "Compiler Design",
        "Computer Architecture",
        "Computer Graphics",
        "Computer Organization and Design",
        "Computing fundamentals",
        "Concurrency Design Patterns",
        "Creational Design Patterns",
        "Data Structures",
        "Data Structures and Algorithms",
        "Design patterns",
        "Dijkstra",
        "Distributed Services",
        "Functional Programming",
        "GeneralOOP",
        "Mathematica",
        "Mathematics",
        "Object-oriented analysis and design (OOAD)",
        "Object-Oriented Programming",
        "Operating Systems",
        "Scalability",
        "Scientific Computing",
        "Software Architecture",
        "Solutions Architecture",
        "Structural Design Patterns",
        "System Design",
    ],
    "Quantum & Emerging Compute": [
        "Qiskit",
        "Quantum Algorithms",
        "Quantum Computing",
        "Quantum Programming",
    ],
    "Engineering Disciplines": [
        "Aeronautical Engineering",
        "Analog Circuits",
        "Biotechnology Engineering",
        "Chemical Engineering",
        "Civil Engineering",
        "Computer Science Engineering",
        "Electrical and Electronics Engineering",
        "Electrical Engineering",
        "Electronics and Communication Engineering",
        "Instrumentation and Control Engineering",
        "Mechanical Engineering",
        "Structural Engineering",
    ],
    "Project Mgmt, Agile & Process": [
        "Agile Architecture Leadership (SAFe)",
        "Agile Methodology",
        "Audit Management",
        "Certified Scrum Master",
        "Compliance Management",
        "Enterprise Agile Facilitation",
        "ISO Standards",
        "Kanban",
        "Lean",
        "PRINCE2",
        "Procurement and Vendor Management",
        "Product and Portfolio Management",
        "Product Lifecycle Management",
        "Product Owner Certification",
        "Program Management/Product Management",
        "Project management",
        "Project Management & Agile",
        "risk and compliance",
        "Risk and Data Governance",
        "Risk Assessment",
        "SDLC",
        "Six Sigma",
        "Trello",
        "Vendor_Management",
    ],
    "Design & UX": [
        "Design principles",
        "Figma",
        "UI",
        "UI/UX Design Principles",
        "User Experience",
    ],
    "Office & Productivity Tools": [
        "Advance Excel",
        "Asana",
        "Content writing",
        "Documentation",
        "Email writing",
        "Excel",
        "Google Workspace",
        "Microsoft 365",
        "Microsoft Office 365",
        "MS OFFICE",
        "Report Writing",
        "Slack",
        "Technical Writing",
    ],
    "Business & Domain Knowledge": [
        "Account Management",
        "Accounting Fundamentals",
        "Advertising and Communications",
        "Algorithmic Trading",
        "Banking and Financial Services",
        "Bioinformatics",
        "Business Analysis",
        "Business Operations",
        "Business Performance Management",
        "Business Process Configuration",
        "Business Reporting",
        "Business-Technical Translation",
        "Clinical Data Management",
        "Continuous Improvement",
        "Corporate Finance",
        "Customer Complaint Handling",
        "Customer Experience and Service Design",
        "Customer Success Management",
        "Digital Marketing",
        "Education and Learning Technology",
        "Electronic data interchange",
        "Electronic Health Records",
        "Energy and Utilities",
        "ESG and Sustainability",
        "ESG Awareness",
        "Finance and Finance Regulation",
        "Finance Audit",
        "Finance Implementation",
        "Financial Acumen for Non-Finance",
        "Financial Markets",
        "Financial Modeling",
        "Financial Technology",
        "Health Information Systems",
        "Healthcare Technology",
        "Hospitality and Travel Operations",
        "Human Resources and People Operations",
        "Insurance and Risk Management",
        "InsurTech",
        "Key Performance Indicator",
        "Legal and Contract Management",
        "Logistics and Transportation",
        "Manufacturing & Engineering",
        "Manufacturing Execution Systems",
        "Marketing and Brand Management",
        "Media",
        "Medical Device Integration",
        "Mergers and Acquisitions",
        "Nonprofit and Social Impact",
        "Private Equity and Venture Capital",
        "Process Optimization",
        "Product Marketing",
        "Public Sector and Government",
        "Real Estate and Property Management",
        "RegTech",
        "Regulatory Knowledge",
        "Retail and E-commerce Operations",
        "Sales",
        "Sales Management",
        "Specialized Tax Services",
        "Stock Management",
        "Supply Chain and Operations Management",
        "Tax Accountant",
        "Tax Compliance and Regulations",
        "Tax Planning and Strategy",
        "Tax Preparation and Filing",
        "Tax Software and Technology",
        "Taxation",
        "Telemedicine",
        "Trading Systems",
    ],
    "Soft Skills & Behavioral": [
        "Adaptability and Learning Agility",
        "Analytical Thinking",
        "Attention to detail",
        "Coaching and Mentoring",
        "Communication",
        "Communication Skills",
        "Consulting and Advisory",
        "Critical Thinking",
        "Cross-functional Collaboration",
        "Diversity",
        "Emotional Intelligence",
        "Empowerment & Accountability",
        "Equity",
        "Ethics and Professional Conduct",
        "Executive Stakeholder Communication",
        "Facilitation Skills",
        "Feedback and Performance Conversations",
        "Inclusion",
        "Influence",
        "Innovation and Design Thinking",
        "Interviewing and Hiring Skills",
        "Leadership",
        "Leadership and People Management",
        "Negotiation Skills",
        "Personal Branding and Networking",
        "Presentation and Executive Presence",
        "Problem Solving",
        "Remote Work and Virtual Collaboration",
        "Resilience and Wellbeing",
        "SOFT SKILLS",
        "Stakeholder Engagement",
        "Stakeholder Management",
        "Strategic thinking & planning",
        "Stress-management",
        "Team Handling",
        "Team Management",
        "Teamwork and Collaboration",
        "Time Management and Productivity",
    ],
    "Aptitude & Verbal": [
        "CEFR",
        "Logical Reasoning",
        "Quantitative Aptitude",
        "Verbal Ability",
    ],
}
