"""add skill graph tables

Revision ID: 017629e138f6
Revises: bdf71a9b6777
Create Date: 2026-08-24 10:54:27.929359

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017629e138f6'
down_revision: Union[str, Sequence[str], None] = 'bdf71a9b6777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The team's master skill list — 30 Tech, 25 AI, 10 Non-Tech. AI Engineering
# is the only sub-domain the source list actually splits out.
SKILLS: list[tuple[str, str, str | None]] = [
    (".NET 6.0, ASP.NET Core 8.0, C#", "tech", None),
    ("Angular", "tech", None),
    ("Django", "tech", None),
    ("Flask", "tech", None),
    ("Laravel", "tech", None),
    ("NextJS", "tech", None),
    ("NodeJS", "tech", None),
    ("ReactJS", "tech", None),
    ("Ruby on Rails", "tech", None),
    ("Spring (incl. Spring Boot)", "tech", None),
    ("TypeScript", "tech", None),
    ("VueJS", "tech", None),
    ("Core Java", "tech", None),
    ("JSP", "tech", None),
    ("React with TypeScript", "tech", None),
    ("Go", "tech", None),
    ("React Native", "tech", None),
    ("HTML, CSS, JavaScript", "tech", None),
    (".NET 8.0, C#", "tech", None),
    ("Python", "tech", None),
    (".NET 8.0, VB.NET", "tech", None),
    ("Flutter", "tech", None),
    ("HTML, CSS", "tech", None),
    ("JavaScript", "tech", None),
    ("NestJS", "tech", None),
    ("NuxtJS", "tech", None),
    ("ThreeJS", "tech", None),
    ("HTML", "tech", None),
    ("CSS", "tech", None),
    ("Kotlin", "tech", None),
    ("Artificial Intelligence", "ai", "AI Engineering"),
    ("Agentic AI", "ai", "AI Engineering"),
    ("LLM (Large Language Model)", "ai", "AI Engineering"),
    ("Large Context Model", "ai", "AI Engineering"),
    ("Model Context Protocol", "ai", "AI Engineering"),
    ("Model Governance", "ai", "AI Engineering"),
    ("Model Lifecycle Management", "ai", "AI Engineering"),
    ("Machine Learning Operations", "ai", "AI Engineering"),
    ("Langchain", "ai", "AI Engineering"),
    ("LangGraph", "ai", "AI Engineering"),
    ("GraphAI", "ai", "AI Engineering"),
    ("Prompt Engineering", "ai", "AI Engineering"),
    ("Retrieval-Augmented Generation", "ai", "AI Engineering"),
    ("Transfer Learning", "ai", "AI Engineering"),
    ("Automated Systems", "ai", "AI Engineering"),
    ("Voice Recognition", "ai", "AI Engineering"),
    ("Speech Synthesis", "ai", "AI Engineering"),
    ("Chatbot (incl. Development)", "ai", "AI Engineering"),
    ("Conversational AI", "ai", "AI Engineering"),
    ("Low Code No Code Platforms", "ai", "AI Engineering"),
    ("Power Apps", "ai", "AI Engineering"),
    ("Microsoft Power Automate (incl. Advanced)", "ai", "AI Engineering"),
    ("Google AppSheet", "ai", "AI Engineering"),
    ("Bubble", "ai", "AI Engineering"),
    ("Zapier", "ai", "AI Engineering"),
    ("Communication (Written & Verbal)", "nontech", None),
    ("Leadership and People Management", "nontech", None),
    ("Problem Solving", "nontech", None),
    ("Critical Thinking", "nontech", None),
    ("Emotional Intelligence (EQ)", "nontech", None),
    ("Teamwork and Collaboration", "nontech", None),
    ("Adaptability and Learning Agility", "nontech", None),
    ("Time Management and Productivity", "nontech", None),
    ("Stakeholder Management and Influence", "nontech", None),
    ("Presentation and Executive Presence", "nontech", None),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sub_domain', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('tech', 'ai', 'nontech')", name='ck_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('member_skill_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 5', name='ck_skill_level_range'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'skill_id', name='uq_member_skill')
    )
    op.create_index('ix_skill_ratings_skill', 'member_skill_ratings', ['skill_id'], unique=False)
    # ### end Alembic commands ###

    bind = op.get_bind()
    skills = sa.table(
        "skills",
        sa.column("name", sa.String),
        sa.column("category", sa.String),
        sa.column("sub_domain", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )
    bind.execute(
        skills.insert(),
        [
            {"name": name, "category": category, "sub_domain": sub_domain,
             "sort_order": i, "is_active": True}
            for i, (name, category, sub_domain) in enumerate(SKILLS)
        ],
    )

    # Sreejith files tickets on everyone's behalf (see ANALYTICS.md) but isn't
    # part of the team being rated — pre-excluded from the exercise, same as
    # the admin-editable list this settings row backs from here on.
    sreejith_id = bind.execute(
        sa.text("SELECT id FROM members WHERE display_name = 'Sreejith PV'")
    ).scalar()
    bind.execute(
        sa.text(
            "INSERT INTO integration_settings (key, value) VALUES (:key, :value) "
            "ON CONFLICT (key) DO NOTHING"
        ),
        {
            "key": "skill_graph",
            "value": json.dumps({
                "open_weekdays": [0, 1, 2, 3, 4, 5, 6],
                "excluded_member_ids": [sreejith_id] if sreejith_id else [],
            }),
        },
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_ratings_skill', table_name='member_skill_ratings')
    op.drop_table('member_skill_ratings')
    op.drop_table('skills')
    # ### end Alembic commands ###
    op.execute(sa.text("DELETE FROM integration_settings WHERE key = 'skill_graph'"))
