"""add mcq review jobs and skill taxonomy tags

Revision ID: 09be6dfa1c6d
Revises: 6d88c5d86722
Create Date: 2026-09-15 23:09:51.342140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09be6dfa1c6d'
down_revision: Union[str, Sequence[str], None] = '6d88c5d86722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_taxonomy_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'tag', name='uq_taxonomy_category_tag')
    )
    op.create_index('ix_taxonomy_category', 'skill_taxonomy_tags', ['category'], unique=False)
    op.create_table('mcq_review_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'parsing', 'parsed', 'reviewing', 'done', 'failed')", name='ck_status'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcq_jobs_user_created', 'mcq_review_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mcq_review_jobs_created_at'), 'mcq_review_jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcq_review_jobs_created_at'), table_name='mcq_review_jobs')
    op.drop_index('ix_mcq_jobs_user_created', table_name='mcq_review_jobs')
    op.drop_table('mcq_review_jobs')
    op.drop_index('ix_taxonomy_category', table_name='skill_taxonomy_tags')
    op.drop_table('skill_taxonomy_tags')
    # ### end Alembic commands ###
