"""add content health tables

Revision ID: 2b05aae1d83f
Revises: a1c93f7b2e04
Create Date: 2026-09-02 12:56:52.378587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b05aae1d83f'
down_revision: Union[str, Sequence[str], None] = 'a1c93f7b2e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_health_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('total_slugs', sa.Integer(), nullable=False),
    sa.Column('slugs_with_rating', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_from', 'period_to')
    )
    op.create_table('content_health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('problem_type', sa.String(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.Column('tests_published', sa.Integer(), nullable=True),
    sa.Column('tests_with_qt', sa.Integer(), nullable=True),
    sa.Column('tests_with_library', sa.Integer(), nullable=True),
    sa.Column('library_questions_used', sa.Integer(), nullable=True),
    sa.Column('candidates_attempted', sa.Integer(), nullable=True),
    sa.Column('top_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_from', 'period_to', 'problem_type')
    )
    op.create_table('content_health_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('problem_type', sa.String(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('questions', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('dead_pct', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('att_per_q', sa.Float(), nullable=False),
    sa.Column('avg_health', sa.Float(), nullable=True),
    sa.Column('difficulty_easy', sa.Integer(), nullable=False),
    sa.Column('difficulty_medium', sa.Integer(), nullable=False),
    sa.Column('difficulty_hard', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_from', 'period_to', 'problem_type', 'topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_health_topics')
    op.drop_table('content_health_snapshots')
    op.drop_table('content_health_feedback')
    # ### end Alembic commands ###
