"""scheduled posting and opt-in jira tickets

Revision ID: 2bbdc0a17f9b
Revises: 4e9031f493b5
Create Date: 2026-08-10 12:28:17.143528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbdc0a17f9b'
down_revision: Union[str, Sequence[str], None] = '4e9031f493b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_entries', sa.Column('post_at', sa.DateTime(), nullable=True))
    op.add_column('daily_entries', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('entry_items', sa.Column('jira_wanted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_items', 'jira_wanted')
    op.drop_column('daily_entries', 'posted_at')
    op.drop_column('daily_entries', 'post_at')
    # ### end Alembic commands ###
