"""add event question review tables

Revision ID: 2dc6c0e9bd84
Revises: f2f931efc5e5
Create Date: 2026-09-24 12:25:14.969669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dc6c0e9bd84'
down_revision: Union[str, Sequence[str], None] = 'f2f931efc5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reviews',
    sa.Column('setter_template_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('workspace', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('library_type', sa.String(), nullable=True),
    sa.Column('content_created_at', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_verdict', sa.String(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_slug', sa.String(), nullable=True),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('l1_assignee_id', sa.Integer(), nullable=True),
    sa.Column('l1_status', sa.String(), nullable=False),
    sa.Column('l1_comments', sa.Text(), nullable=True),
    sa.Column('l2_assignee_id', sa.Integer(), nullable=True),
    sa.Column('l2_status', sa.String(), nullable=False),
    sa.Column('l2_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("l1_status IN ('not_started', 'in_progress', 'done')", name='ck_l1_status'),
    sa.CheckConstraint("l2_status IN ('not_requested', 'pending', 'in_progress', 'done')", name='ck_l2_status'),
    sa.CheckConstraint("last_verdict IN ('no_issue_found', 'fixed', 'removed')", name='ck_last_verdict'),
    sa.ForeignKeyConstraint(['l1_assignee_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l2_assignee_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('setter_template_id')
    )
    op.create_table('question_review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_template_id', sa.Integer(), nullable=False),
    sa.Column('event_slug', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('actor_member_id', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('l1', 'l2')", name='ck_level'),
    sa.CheckConstraint("verdict IN ('no_issue_found', 'fixed', 'removed')", name='ck_verdict'),
    sa.ForeignKeyConstraint(['actor_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setter_template_id'], ['question_reviews.setter_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qre_setter_created', 'question_review_events', ['setter_template_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_question_review_events_created_at'), 'question_review_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_review_events_created_at'), table_name='question_review_events')
    op.drop_index('ix_qre_setter_created', table_name='question_review_events')
    op.drop_table('question_review_events')
    op.drop_table('question_reviews')
    # ### end Alembic commands ###
