"""capture jira timestamps, priority, sla and time-in-status

Revision ID: 4e9031f493b5
Revises: e8ddb16eebfa
Create Date: 2026-08-10 11:24:01.022194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9031f493b5'
down_revision: Union[str, Sequence[str], None] = 'e8ddb16eebfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_items', sa.Column('external_created_at', sa.DateTime(), nullable=True))
    op.add_column('entry_items', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('entry_items', sa.Column('resolution', sa.String(), nullable=True))
    op.add_column('entry_items', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('entry_items', sa.Column('sla_met', sa.Boolean(), nullable=True))
    op.add_column('entry_items', sa.Column('time_in_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_items', 'time_in_status')
    op.drop_column('entry_items', 'sla_met')
    op.drop_column('entry_items', 'priority')
    op.drop_column('entry_items', 'resolution')
    op.drop_column('entry_items', 'resolved_at')
    op.drop_column('entry_items', 'external_created_at')
    # ### end Alembic commands ###
