"""pipeline as free slug, keep jira issue type

Revision ID: 52f3183feaec
Revises: a844b92e9a50
Create Date: 2026-08-06 13:40:30.701883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f3183feaec'
down_revision: Union[str, Sequence[str], None] = 'a844b92e9a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_items', sa.Column('external_issue_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_items', 'external_issue_type')
    # ### end Alembic commands ###
