"""add event review sync cache

Revision ID: 699fb7de915f
Revises: 2dc6c0e9bd84
Create Date: 2026-09-24 18:29:06.250473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '699fb7de915f'
down_revision: Union[str, Sequence[str], None] = '2dc6c0e9bd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_review_syncs',
    sa.Column('event_slug', sa.String(), nullable=False),
    sa.Column('setter_template_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_review_syncs')
    # ### end Alembic commands ###
