"""add content issues

Revision ID: 6d88c5d86722
Revises: 2b05aae1d83f
Create Date: 2026-09-04 11:55:40.599242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d88c5d86722"
down_revision: Union[str, Sequence[str], None] = "2b05aae1d83f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_issues",
        sa.Column("issue_key", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content_issue_status", sa.String(), nullable=False),
        sa.Column("setter", sa.String(), nullable=True),
        sa.Column("setter_last_modified", sa.String(), nullable=True),
        sa.Column("test_slugs_impacted", sa.Integer(), nullable=False),
        sa.Column("candidates_impacted", sa.Integer(), nullable=False),
        sa.Column("customers_impacted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("issue_key"),
    )
    op.create_index(
        "ix_content_issues_created", "content_issues", ["created_at"], unique=False
    )
    op.create_index(
        "ix_content_issues_status",
        "content_issues",
        ["content_issue_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_issues_status", table_name="content_issues")
    op.drop_index("ix_content_issues_created", table_name="content_issues")
    op.drop_table("content_issues")
    # ### end Alembic commands ###
