"""multi-select question types

Revision ID: 86d37869cb53
Revises: 18d9191557ed
Create Date: 2026-08-24 12:17:16.785357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d37869cb53'
down_revision: Union[str, Sequence[str], None] = '18d9191557ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_item_question_types',
    sa.Column('entry_item_id', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_item_id'], ['entry_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_item_id', 'question_type_id')
    )
    # Carry every existing single choice across before the column holding it
    # goes away — Jira's own question-type field was always a multi-select
    # picklist, this just stops us collapsing it to one on the way in.
    op.execute(
        "INSERT INTO entry_item_question_types (entry_item_id, question_type_id) "
        "SELECT id, question_type_id FROM entry_items WHERE question_type_id IS NOT NULL"
    )
    op.drop_constraint(op.f('entry_items_question_type_id_fkey'), 'entry_items', type_='foreignkey')
    op.drop_column('entry_items', 'question_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_items', sa.Column('question_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('entry_items_question_type_id_fkey'), 'entry_items', 'question_types', ['question_type_id'], ['id'])
    # Lossy by nature — a single column can't hold what became a multi-select.
    # Picks the lowest id per item so the downgrade is at least deterministic.
    op.execute(
        "UPDATE entry_items SET question_type_id = sub.question_type_id FROM ("
        "SELECT DISTINCT ON (entry_item_id) entry_item_id, question_type_id "
        "FROM entry_item_question_types ORDER BY entry_item_id, question_type_id"
        ") sub WHERE entry_items.id = sub.entry_item_id"
    )
    op.drop_table('entry_item_question_types')
    # ### end Alembic commands ###
