"""remove AE daily tracking

Revision ID: a707eb4497f0
Revises: b5d10f969b44
Create Date: 2026-08-06 12:51:25.641675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a707eb4497f0'
down_revision: Union[str, Sequence[str], None] = 'b5d10f969b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ae_daily_metrics carries FKs into the other two, so it goes first.
    op.drop_table('ae_daily_metrics')
    op.drop_index(op.f('ix_ae_date'), table_name='ae_daily_updates')
    op.drop_table('ae_daily_updates')
    op.drop_table('ae_metric_definitions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ae_daily_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ae_daily_update_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('value >= 0', name=op.f('ck_ae_value_positive')),
    sa.ForeignKeyConstraint(['ae_daily_update_id'], ['ae_daily_updates.id'], name=op.f('ae_daily_metrics_ae_daily_update_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['ae_metric_definitions.id'], name=op.f('ae_daily_metrics_metric_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ae_daily_metrics_pkey')),
    sa.UniqueConstraint('ae_daily_update_id', 'metric_id', name=op.f('uq_ae_metric'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ae_metric_definitions',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ae_metric_definitions_pkey')),
    sa.UniqueConstraint('key', name=op.f('ae_metric_definitions_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('ae_metric_definitions_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ae_daily_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], name=op.f('ae_daily_updates_created_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('ae_daily_updates_member_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('ae_daily_updates_pkey')),
    sa.UniqueConstraint('member_id', 'entry_date', name=op.f('uq_ae_member_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ae_date'), 'ae_daily_updates', ['entry_date'], unique=False)
    # ### end Alembic commands ###
