
"""add pipeline, effort flags, jira account ids and member aliases

Revision ID: a844b92e9a50
Revises: a707eb4497f0
Create Date: 2026-08-06 13:01:05.849939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a844b92e9a50'
down_revision: Union[str, Sequence[str], None] = 'a707eb4497f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.add_column('entry_items', sa.Column('effort_suspect', sa.Boolean(), nullable=False,
                                          server_default=sa.text('false')))
    op.add_column('entry_items', sa.Column('pipeline', sa.String(), nullable=False,
                                          server_default=sa.text("'content_task'")))
    op.add_column('entry_items', sa.Column('external_status', sa.String(), nullable=True))
    op.create_index('ix_items_pipeline', 'entry_items', ['pipeline'], unique=False)
    op.add_column('members', sa.Column('jira_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'jira_account_id')
    op.drop_index('ix_items_pipeline', table_name='entry_items')
    op.drop_column('entry_items', 'external_status')
    op.drop_column('entry_items', 'pipeline')
    op.drop_column('entry_items', 'effort_suspect')
    op.drop_table('member_aliases')
    # ### end Alembic commands ###
