"""add effort minutes to entry items

Revision ID: b5d10f969b44
Revises: dd5699bdd09e
Create Date: 2026-08-05 12:17:03.034397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d10f969b44'
down_revision: Union[str, Sequence[str], None] = 'dd5699bdd09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The autogenerate also proposed dropping and recreating uq_members_name_ci
    # purely because Postgres echoes the expression as TRIM(BOTH FROM ...).
    # Same index, different spelling — dropped from this migration.
    op.add_column('entry_items', sa.Column('effort_minutes', sa.Integer(), nullable=True))
    op.create_check_constraint(
        'ck_effort_non_negative', 'entry_items',
        'effort_minutes IS NULL OR effort_minutes >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_effort_non_negative', 'entry_items', type_='check')
    op.drop_column('entry_items', 'effort_minutes')
    # ### end Alembic commands ###
