"""add parent issue link to entry items

Revision ID: bdf71a9b6777
Revises: ff6abfd6793f
Create Date: 2026-08-18 12:01:06.434900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf71a9b6777'
down_revision: Union[str, Sequence[str], None] = 'ff6abfd6793f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_items', sa.Column('parent_issue_key', sa.String(), nullable=True))
    op.add_column('entry_items', sa.Column('parent_issue_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_items', 'parent_issue_url')
    op.drop_column('entry_items', 'parent_issue_key')
    # ### end Alembic commands ###
