"""initial schema

Revision ID: dd5699bdd09e
Revises: 
Create Date: 2026-08-04 20:00:15.561398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd5699bdd09e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ae_metric_definitions',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_requests',
    sa.Column('issue_key', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_category', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('reporter', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('issue_key')
    )
    op.create_index('ix_cr_assignee', 'content_requests', ['assignee'], unique=False)
    op.create_index('ix_cr_created', 'content_requests', ['created_at'], unique=False)
    op.create_index('ix_cr_status', 'content_requests', ['status'], unique=False)
    op.create_table('integration_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('question_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('slack_day_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('parent_ts', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_date', 'kind', 'channel', name='uq_slack_day')
    )
    op.create_table('sync_cursors',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('slack_user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('content', 'ae', 'manager', 'admin')", name='ck_role'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_members_active_role', 'members', ['is_active', 'role'], unique=False)
    op.create_index('uq_members_name_ci', 'members', [sa.literal_column('lower(trim(display_name))')], unique=True)
    op.create_table('oauth_account',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('ae_daily_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'entry_date', name='uq_ae_member_date')
    )
    op.create_index('ix_ae_date', 'ae_daily_updates', ['entry_date'], unique=False)
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('slack_reply_ts', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('plan', 'update')", name='ck_kind'),
    sa.CheckConstraint("source IN ('web', 'slack', 'api', 'import')", name='ck_source'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'blocked', 'closed')", name='ck_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_entries_date_kind', 'daily_entries', ['entry_date', 'kind'], unique=False)
    op.create_index('ix_entries_member_date', 'daily_entries', ['member_id', 'entry_date'], unique=False)
    op.create_index('uq_entries_one_plan', 'daily_entries', ['member_id', 'entry_date'], unique=True, postgresql_where=sa.text("kind = 'plan'"))
    op.create_table('ae_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ae_daily_update_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_ae_value_positive'),
    sa.ForeignKeyConstraint(['ae_daily_update_id'], ['ae_daily_updates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['ae_metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ae_daily_update_id', 'metric_id', name='uq_ae_metric')
    )
    op.create_table('entry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=True),
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(), nullable=True),
    sa.Column('jira_issue_url', sa.String(), nullable=True),
    sa.Column('jira_state', sa.String(), nullable=False),
    sa.Column('jira_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jira_state IN ('none', 'pending', 'ok', 'failed')", name='ck_jira_state'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'blocked', 'closed')", name='ck_status'),
    sa.CheckConstraint('count IS NULL OR count > 0', name='ck_count_positive'),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['entry_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_customer', 'entry_items', ['customer'], unique=False)
    op.create_index('ix_items_entry', 'entry_items', ['entry_id'], unique=False)
    op.create_index('ix_items_jira_retry', 'entry_items', ['jira_state'], unique=False, postgresql_where=sa.text("jira_state IN ('pending', 'failed')"))
    op.create_index('ix_items_plan_item', 'entry_items', ['plan_item_id'], unique=False)
    op.create_index('ix_items_status_due', 'entry_items', ['status', 'due_at'], unique=False)
    op.create_table('entry_item_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_item_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_item_id'], ['entry_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_item_status_events_changed_at'), 'entry_item_status_events', ['changed_at'], unique=False)
    op.create_index('ix_status_events_item', 'entry_item_status_events', ['entry_item_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_events_item', table_name='entry_item_status_events')
    op.drop_index(op.f('ix_entry_item_status_events_changed_at'), table_name='entry_item_status_events')
    op.drop_table('entry_item_status_events')
    op.drop_index('ix_items_status_due', table_name='entry_items')
    op.drop_index('ix_items_plan_item', table_name='entry_items')
    op.drop_index('ix_items_jira_retry', table_name='entry_items', postgresql_where=sa.text("jira_state IN ('pending', 'failed')"))
    op.drop_index('ix_items_entry', table_name='entry_items')
    op.drop_index('ix_items_customer', table_name='entry_items')
    op.drop_table('entry_items')
    op.drop_table('ae_daily_metrics')
    op.drop_index('uq_entries_one_plan', table_name='daily_entries', postgresql_where=sa.text("kind = 'plan'"))
    op.drop_index('ix_entries_member_date', table_name='daily_entries')
    op.drop_index('ix_entries_date_kind', table_name='daily_entries')
    op.drop_table('daily_entries')
    op.drop_index('ix_ae_date', table_name='ae_daily_updates')
    op.drop_table('ae_daily_updates')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_index('uq_members_name_ci', table_name='members')
    op.drop_index('ix_members_active_role', table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task_types')
    op.drop_table('sync_cursors')
    op.drop_table('slack_day_threads')
    op.drop_table('question_types')
    op.drop_table('integration_settings')
    op.drop_index('ix_cr_status', table_name='content_requests')
    op.drop_index('ix_cr_created', table_name='content_requests')
    op.drop_index('ix_cr_assignee', table_name='content_requests')
    op.drop_table('content_requests')
    op.drop_table('ae_metric_definitions')
    # ### end Alembic commands ###
