"""add event review import jobs table

Revision ID: e413db3dd008
Revises: 699fb7de915f
Create Date: 2026-09-24 21:00:39.227061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e413db3dd008'
down_revision: Union[str, Sequence[str], None] = '699fb7de915f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_review_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'validating', 'ready_for_review', 'importing', 'done', 'error')", name='ck_status'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eqr_import_jobs_user_created', 'event_review_import_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_review_import_jobs_created_at'), 'event_review_import_jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_review_import_jobs_created_at'), table_name='event_review_import_jobs')
    op.drop_index('ix_eqr_import_jobs_user_created', table_name='event_review_import_jobs')
    op.drop_table('event_review_import_jobs')
    # ### end Alembic commands ###
