"""capture jira request type

Revision ID: e8ddb16eebfa
Revises: fa0685e9f2fd
Create Date: 2026-08-06 15:34:39.246372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ddb16eebfa'
down_revision: Union[str, Sequence[str], None] = 'fa0685e9f2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_items', sa.Column('request_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_items', 'request_type')
    # ### end Alembic commands ###
