"""add source_file to mcq_review_jobs

Revision ID: f2f931efc5e5
Revises: 09be6dfa1c6d
Create Date: 2026-09-17 11:54:32.087167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f931efc5e5'
down_revision: Union[str, Sequence[str], None] = '09be6dfa1c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcq_review_jobs', sa.Column('source_file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcq_review_jobs', 'source_file')
    # ### end Alembic commands ###
