"""add weekly plan items

Revision ID: ff6abfd6793f
Revises: 416250145d5e
Create Date: 2026-08-17 20:48:56.655244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6abfd6793f'
down_revision: Union[str, Sequence[str], None] = '416250145d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('achievement', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('yet_to_start', 'in_progress', 'blocked', 'completed')", name='ck_status'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_plan_member_week', 'weekly_plan_items', ['member_id', 'week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_plan_member_week', table_name='weekly_plan_items')
    op.drop_table('weekly_plan_items')
    # ### end Alembic commands ###
